const musicInfoList = [
  {
    id: 0,
    image: "",
    audio: "/music/song_0.mp3",
    song: "哪吒",
    album: "",
    singer: "戴荃",
  },
  {
    id: 1,
    image: "",
    audio: "/music/song_1.mp3",
    song: "那盏茶",
    album: "",
    singer: "金志文",
  },
  {
    id: 2,
    image: "",
    audio: "/music/song_2.mp3",
    song: "明月天涯",
    album: "",
    singer: "李常超(Lao乾妈)满汉全席",
  },
  {
    id: 3,
    image: "",
    audio: "/music/song_3.mp3",
    song: "梅雨声",
    album: "",
    singer: "莫小娘",
  },
  {
    id: 4,
    image: "",
    audio: "/music/song_4.mp3",
    song: "栖凰",
    album: "",
    singer: "漆柚",
  },
  {
    id: 5,
    image: "",
    audio: "/music/song_5.mp3",
    song: "齐天(Cover:大冢爱)",
    album: "",
    singer: "兔裹煎蛋卷",
  },
  {
    id: 6,
    image: "",
    audio: "/music/song_6.mp3",
    song: "木兰行",
    album: "",
    singer: "忘川风华录,苍穹",
  },
  {
    id: 7,
    image: "",
    audio: "/music/song_7.mp3",
    song: "哪吒",
    album: "",
    singer: "GAI周延，大痒痒",
  },
  {
    id: 8,
    image: "",
    audio: "/music/song_8.mp3",
    song: "千梦[with.Aki阿杰]",
    album: "",
    singer: "HITA",
  },
];
export { musicInfoList };
